### ISSUE TITLE
I do not want "Green Paper".

### ISSUE THREAD

**Issue by wizzwizz4** [aloisdg/Pizzule#10]
Attempted to order "Green Peppers", received a pizza covered in mouldy newspaper. Would not buy again.

**Comment by aloisdg** [comment]
hello fellow human!

It was not a mistake (of course). I like to write when I eat a pizza. So I want to be able to order some papers. Also, thank you for pointing a terrible mistake. How can we call ourself a serious pizza maker if we forget "Green Peppers"? I will fix this right now!

Cheers,
